### ISSUE TITLE
test of llvm_mode fails

### ISSUE THREAD

**Issue by msoos** [carolemieux/perffuzz#7]
Hi, 

On a recent Arch Linux, when building `llvm_mode`, I'm getting:

```
soos@vvv-dejavu:llvm_mode$ make
[*] Checking for working 'llvm-config'...
[*] Checking for working 'clang'...
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  afl-clang-fast.c -o ../afl-clang-fast 
ln -sf afl-clang-fast ../afl-clang-fast++
clang++ `llvm-config --cxxflags` -fno-rtti -fpic -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"2.52b\" -Wno-variadic-macros -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config --ldflags` 
clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  -fPIC -shared afl-catch-dlclose.so.c -o ../afl-catch-dlclose.so
clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  -fPIC -c afl-llvm-rt.o.c -o ../afl-llvm-rt.o
afl-llvm-rt.o.c:99:20: warning: incompatible pointer types assigning to 'u32 *' (aka 'unsigned int *') from 'u8 *' (aka 'unsigned char *') [-Wincompatible-pointer-types]
    __afl_perf_ptr = &__afl_area_ptr[MAP_SIZE];
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[*] Building 32-bit variant of the runtime (-m32)... success!
[*] Building 64-bit variant of the runtime (-m64)... success!
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN AFL_INST_RATIO; AFL_QUIET=1 AFL_PATH=. AFL_CC=clang ../afl-clang-fast -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  ../test-instr.c -o test-instr 
echo 0 | ../afl-showmap -m none -q -o .test-instr0 ./test-instr
echo 1 | ../afl-showmap -m none -q -o .test-instr1 ./test-instr

Oops, the instrumentation does not seem to be behaving correctly!

Please ping <lcamtuf@google.com> to troubleshoot the issue.

make: *** [Makefile:105: test_build] Error 1**
```

It was a full normal compile, so I'm a bit confused. Is the test incorrectly set up for perffuzz and hasn't been changed/fixed?

**Comment by carolemieux** [comment]
What version of arch are you using? What is your LLVM/clang version?

**Comment by msoos** [comment]
Hi,

```
soos@vvv-dejavu:~$ clang --version
clang version 9.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
soos@vvv-dejavu:~$ clang++ --version
clang version 9.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

This is latest Arch linux clang version.

**Comment by carolemieux** [comment]
Thanks.

I'm getting the same error on Ubuntu with clang 11, and another one on my mac with clang 11. I presume the root cause is the same. I will investigate.

**Comment by carolemieux** [comment]
In the meantime, you can also check out FuzzFactory's `perf` domain:
https://github.com/rohanpadhye/FuzzFactory
The fuzzing algorithm is nearly identical to PerfFuzz, but this one focuses on excessive hits of basic blocks rather than basic block transitions.

**Comment by carolemieux** [comment]
The issue is fixed on my Ubuntu box in 9cdd44a

Let me know if that resolved it for you as well. 



To check whether perffuzz is working correctly, you can try:
```
./afl-clang-fast insertion-sort.c -o isort

mkdir isort-seeds
head -c 64 /dev/zero > seeds/zeroes

./afl-fuzz -p -i isort-seeds -o isort_perf_test/ -N 64 ./isort @@
```
You should see the number of `total paths` (this is a misnomer; it's just the number of saved inputs) increase consistently. You can also check to see if the saved inputs are heading towards a worst-case by running
```
for i in isort_perf_test/queue/id*; do ./isort $i | grep comps; done
```
(which, for each saved input, plots the number of comparisons insertion sort performed while sorting that input) 

For comparison with the performance compared to regular afl, you can run:
```./afl-fuzz -i isort-seeds -o isort_afl_test/ -N 64 ./isort @@```
without the -p option, this should just run regular AFL. You should see `total_paths` quickly topping out around ~20 or so, and the number of cycles increase a lot. There will probably be much fewer comparisons performed for the saved input as well.

**Comment by msoos** [comment]
Wow, that worked perfectly, thank you! Both the fix, and the test case. By the way, this is such a great write-up of the test case, it'd be great to include that in the README! It would certainly have helped me understand the use-case of the tool better. (slight note: you have a slight typo, you wrote `head -c 64 /dev/zero > seeds/zeroes` but it's probably `head -c 64 /dev/zero > isort-seeds/zeroes`). I also liked the topping off and the steady increase with AFL but not with Peffuzz, it's really a great example, I strongly suggest you add it to the bottom of the file because to me it shows the strength of the tool through an example that's easy to interpret.

Anyway, I'm closing this as it's all fixed. Thanks so much! I'll use it on my tool and hopefully find some bugs :)

**Comment by carolemieux** [comment]
Haha, thanks for the tip. Yeah, while writing it up I thought "doesn't this exist in my readme??"
