### ISSUE TITLE
What is Perf_Mask in the instrumentation pass?

### ISSUE THREAD

**Issue by zhanggenex** [carolemieux/perffuzz#8]
Hey, I am trying to do some thing new on PerfFuzz. But there is one thing in the code I am confused.

What is the purpose of this `Perf_Mask`?
https://github.com/carolemieux/perffuzz/blob/f937f370555d0c54f2109e3b1aa5763f8defe337/llvm_mode/afl-llvm-pass.so.cc#L129

I don't think it is correct to add `Perf_Mask` to `Edge_Id` to create a GEP instruction in `PerfBranchPtr` https://github.com/carolemieux/perffuzz/blob/f937f370555d0c54f2109e3b1aa5763f8defe337/llvm_mode/afl-llvm-pass.so.cc#L176
https://github.com/carolemieux/perffuzz/blob/f937f370555d0c54f2109e3b1aa5763f8defe337/llvm_mode/afl-llvm-pass.so.cc#L177

However, `EdgeId % PERF_SIZE` is acctually needed to index the perf map.

Looking forward to your reply, thanks.

**Comment by rohanpadhye** [comment]
> I don't think it is correct to add Perf_Mask to Edge_Id

There is no addition happening here. On line 177, we perform a bitwise-AND of PerfMask and EdgeId. 

`PerfMask = PERF_SIZE - 1`. We assume PERF_SIZE Is a power of 2. So if PERF_SIZE is 2^16 then PerfMap = 2^16-1 = 0xFFFF. So, `PerfMask AND EdgeID` results in keeping only the bottom 16 bits of the EdgeId, thereby ensuring that the GEP instruction is within bounds.
